<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:actormapping="http://www.bonitasoft.org/ns/actormapping/6.0" xmlns:configuration="http://www.bonitasoft.org/ns/studio/configuration" xmlns:connectorconfiguration="http://wwww.bonitasoft.org/model/connector/configuration" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:definition="http://www.bonitasoft.org/ns/connector/definition/6.1" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/studio/process" xsi:schemaLocation="http://www.bonitasoft.org/ns/studio/process/decision http://www.bonitasoft.org/ns/studio/process#//decision">
  <process:MainProcess xmi:id="_eA-lwMziEe22052-PBnc4Q" name="AdmitirPaciente" bonitaModelVersion="7.12.0-004">
    <elements xmi:type="process:Pool" xmi:id="_eA-lwcziEe22052-PBnc4Q" name="Pool">
      <elements xmi:type="process:Lane" xmi:id="_eA-lwsziEe22052-PBnc4Q" name="Totem" actor="_eA_z7cziEe22052-PBnc4Q">
        <elements xmi:type="process:StartEvent" xmi:id="_eA-lw8ziEe22052-PBnc4Q" name="Inicio" outgoing="_4S-T0M2bEe2r5bmlX6-2kg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_eA-lxMziEe22052-PBnc4Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_eA-lxcziEe22052-PBnc4Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_eA-lxsziEe22052-PBnc4Q" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:TextAnnotation" xmi:id="_1g1eQMzpEe22052-PBnc4Q" text="Valida IP y Configuracion de Papel de Totem"/>
        <elements xmi:type="process:Activity" xmi:id="_EoYEsM1kEe2_GaC9xHNsqQ" name="Mostrar listado de prioridades" outgoing="_QL_8EM1oEe2_GaC9xHNsqQ" incoming="_s4RiAM1iEe2_GaC9xHNsqQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_s4LbYc1iEe2_GaC9xHNsqQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_s4LbYM1iEe2_GaC9xHNsqQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_s4LbYs1iEe2_GaC9xHNsqQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_s4LbY81iEe2_GaC9xHNsqQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_s4LbZM1iEe2_GaC9xHNsqQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_s4LbZc1iEe2_GaC9xHNsqQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_s4LbZ81iEe2_GaC9xHNsqQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_s4LbZs1iEe2_GaC9xHNsqQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Activity" xmi:id="_HPeCwM1kEe2_GaC9xHNsqQ" name="Asignar datos de checkin" outgoing="_wP9aEM1jEe2_GaC9xHNsqQ" incoming="_Swi8cM1oEe2_GaC9xHNsqQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_rbtn8s1jEe2_GaC9xHNsqQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_rbtn8c1jEe2_GaC9xHNsqQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_rbtn881jEe2_GaC9xHNsqQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_rbtn9M1jEe2_GaC9xHNsqQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_rbtn9c1jEe2_GaC9xHNsqQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_rbtn9s1jEe2_GaC9xHNsqQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_rbtn-M1jEe2_GaC9xHNsqQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_rbtn981jEe2_GaC9xHNsqQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Activity" xmi:id="_ICNuUM1kEe2_GaC9xHNsqQ" name="Imprimir ticket" outgoing="_JYF8IM1kEe2_GaC9xHNsqQ" incoming="_wP9aEM1jEe2_GaC9xHNsqQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_wP6Wwc1jEe2_GaC9xHNsqQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_wP6WwM1jEe2_GaC9xHNsqQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_wP6Wws1jEe2_GaC9xHNsqQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_wP6Ww81jEe2_GaC9xHNsqQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_wP6WxM1jEe2_GaC9xHNsqQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_wP6Wxc1jEe2_GaC9xHNsqQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_wP6Wx81jEe2_GaC9xHNsqQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_wP6Wxs1jEe2_GaC9xHNsqQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Activity" xmi:id="_M9O20M1kEe2_GaC9xHNsqQ" name="Mostrar pantalla final" outgoing="_SQOacM1kEe2_GaC9xHNsqQ" incoming="_JYF8IM1kEe2_GaC9xHNsqQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_JYBqss1kEe2_GaC9xHNsqQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_JYBqsc1kEe2_GaC9xHNsqQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_JYBqs81kEe2_GaC9xHNsqQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_JYBqtM1kEe2_GaC9xHNsqQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_JYBqtc1kEe2_GaC9xHNsqQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_JYBqts1kEe2_GaC9xHNsqQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_JYBquM1kEe2_GaC9xHNsqQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_JYBqt81kEe2_GaC9xHNsqQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:IntermediateCatchTimerEvent" xmi:id="_PL5t0M1kEe2_GaC9xHNsqQ" name="Aguarda 5 seg" outgoing="_jTIh0M1kEe2_GaC9xHNsqQ" incoming="_SQOacM1kEe2_GaC9xHNsqQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_PMRhQc1kEe2_GaC9xHNsqQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_PMRhQM1kEe2_GaC9xHNsqQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_PMSIUM1kEe2_GaC9xHNsqQ" name="" content="" returnTypeFixed="true"/>
          <condition xmi:type="expression:Expression" xmi:id="_VS-ZwM1kEe2_GaC9xHNsqQ" name="00:00:05" content="5000L" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Long"/>
        </elements>
        <elements xmi:type="process:EndTerminatedEvent" xmi:id="_ho-tIM1kEe2_GaC9xHNsqQ" name="Fin" incoming="_jTIh0M1kEe2_GaC9xHNsqQ _mthlEM1kEe2_GaC9xHNsqQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_ho-tIs1kEe2_GaC9xHNsqQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_ho-tIc1kEe2_GaC9xHNsqQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_ho-tI81kEe2_GaC9xHNsqQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_gyqeQM1mEe2_GaC9xHNsqQ" name="Es valido?" outgoing="_FxEykMzqEe22052-PBnc4Q _44t4MM4qEe2v9Z4_FCyumw" incoming="_pZp5oM5gEe2loO5JO7P1nQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_mGkIoszpEe22052-PBnc4Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_mGkIoczpEe22052-PBnc4Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_mGkIo8zpEe22052-PBnc4Q" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_BVeCEM4rEe2v9Z4_FCyumw" name="Mostrar pantalla con mensaje de totem no valido" outgoing="_mthlEM1kEe2_GaC9xHNsqQ" incoming="_FxEykMzqEe22052-PBnc4Q" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_D53ZUszqEe22052-PBnc4Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_D53ZUczqEe22052-PBnc4Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_D53ZU8zqEe22052-PBnc4Q" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_D53ZVMzqEe22052-PBnc4Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_D53ZVczqEe22052-PBnc4Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_D53ZVszqEe22052-PBnc4Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_D53ZWMzqEe22052-PBnc4Q" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_D53ZV8zqEe22052-PBnc4Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_BVgeWc4rEe2v9Z4_FCyumw">
            <targetForm xmi:type="expression:Expression" xmi:id="_DD9kMM4rEe2v9Z4_FCyumw" name="newForm" content="c0995036-d09e-4225-8d91-2d678620de6b" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_BVgeWM4rEe2v9Z4_FCyumw"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_BVgeW84rEe2v9Z4_FCyumw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_pZYM0M5gEe2loO5JO7P1nQ" name="Validar Totem" outgoing="_pZp5oM5gEe2loO5JO7P1nQ" incoming="_4S-T0M2bEe2r5bmlX6-2kg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_pZYz4c5gEe2loO5JO7P1nQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_pZYz4M5gEe2loO5JO7P1nQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_pZYz4s5gEe2loO5JO7P1nQ" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_1AeqQM5JEe2loO5JO7P1nQ" name="getCurrentTotem" definitionId="rest-get" event="ON_ENTER" definitionVersion="1.2.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_1AeqQc5JEe2loO5JO7P1nQ" definitionId="rest-get" version="1.2.0" modelVersion="7.12.0-004">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_1AeqQs5JEe2loO5JO7P1nQ" key="url">
                <expression xmi:type="expression:Expression" xmi:id="_1AeqQ85JEe2loO5JO7P1nQ" name="validateTotemUrl()" content="import java.net.InetAddress&#xD;&#xA;&#xD;&#xA;def ipAddress = InetAddress.getLocalHost().getHostAddress();&#xD;&#xA;if (ipAddress != null) {&#xD;&#xA;&#x9;return 'https://testcrm-rest.skytel.com.ar:8443/admision/resources/totem-app/totem-full-info/' + ipAddress&#xD;&#xA;}&#xD;&#xA;return 'https://testcrm-rest.skytel.com.ar:8443/admision/resources/totem-app/totem-full-info/192.168.100.41'&#xD;&#xA;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_1AeqRM5JEe2loO5JO7P1nQ" key="urlCookies">
                <expression xmi:type="expression:TableExpression" xmi:id="_1AeqRc5JEe2loO5JO7P1nQ"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_1AeqRs5JEe2loO5JO7P1nQ" key="urlHeaders">
                <expression xmi:type="expression:TableExpression" xmi:id="_1AeqR85JEe2loO5JO7P1nQ"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_1AeqSM5JEe2loO5JO7P1nQ" key="do_not_follow_redirect">
                <expression xmi:type="expression:Expression" xmi:id="_1AeqSc5JEe2loO5JO7P1nQ" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_1AeqSs5JEe2loO5JO7P1nQ" key="ignore_body">
                <expression xmi:type="expression:Expression" xmi:id="_1AeqS85JEe2loO5JO7P1nQ" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_1AeqTM5JEe2loO5JO7P1nQ" key="TLS">
                <expression xmi:type="expression:Expression" xmi:id="_1AeqTc5JEe2loO5JO7P1nQ" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_1AeqTs5JEe2loO5JO7P1nQ" key="hostname_verifier">
                <expression xmi:type="expression:Expression" xmi:id="_1AeqT85JEe2loO5JO7P1nQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_1AeqUM5JEe2loO5JO7P1nQ" key="trust_store_file">
                <expression xmi:type="expression:Expression" xmi:id="_1AeqUc5JEe2loO5JO7P1nQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_1AeqUs5JEe2loO5JO7P1nQ" key="trust_store_password">
                <expression xmi:type="expression:Expression" xmi:id="_1AeqU85JEe2loO5JO7P1nQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_1AeqVM5JEe2loO5JO7P1nQ" key="key_store_file">
                <expression xmi:type="expression:Expression" xmi:id="_1AeqVc5JEe2loO5JO7P1nQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_1AeqVs5JEe2loO5JO7P1nQ" key="key_store_password">
                <expression xmi:type="expression:Expression" xmi:id="_1AeqV85JEe2loO5JO7P1nQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_1AeqWM5JEe2loO5JO7P1nQ" key="auth_type">
                <expression xmi:type="expression:Expression" xmi:id="_1AeqWc5JEe2loO5JO7P1nQ" name="NONE" content="NONE" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_1AeqWs5JEe2loO5JO7P1nQ" key="auth_username">
                <expression xmi:type="expression:Expression" xmi:id="_1AeqW85JEe2loO5JO7P1nQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_1AeqXM5JEe2loO5JO7P1nQ" key="auth_password">
                <expression xmi:type="expression:Expression" xmi:id="_1AeqXc5JEe2loO5JO7P1nQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_1AeqXs5JEe2loO5JO7P1nQ" key="auth_host">
                <expression xmi:type="expression:Expression" xmi:id="_1AeqX85JEe2loO5JO7P1nQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_1AeqYM5JEe2loO5JO7P1nQ" key="auth_port">
                <expression xmi:type="expression:Expression" xmi:id="_1AeqYc5JEe2loO5JO7P1nQ" name="-1" content="-1" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_1AeqYs5JEe2loO5JO7P1nQ" key="auth_realm">
                <expression xmi:type="expression:Expression" xmi:id="_1AeqY85JEe2loO5JO7P1nQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_1AeqZM5JEe2loO5JO7P1nQ" key="auth_preemptive">
                <expression xmi:type="expression:Expression" xmi:id="_1AeqZc5JEe2loO5JO7P1nQ" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_1AeqZs5JEe2loO5JO7P1nQ" key="proxy_protocol">
                <expression xmi:type="expression:Expression" xmi:id="_1AeqZ85JEe2loO5JO7P1nQ" name="HTTP" content="HTTP" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_1AeqaM5JEe2loO5JO7P1nQ" key="proxy_host">
                <expression xmi:type="expression:Expression" xmi:id="_1Aeqac5JEe2loO5JO7P1nQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_1Aeqas5JEe2loO5JO7P1nQ" key="proxy_port">
                <expression xmi:type="expression:Expression" xmi:id="_1Aeqa85JEe2loO5JO7P1nQ" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_1AeqbM5JEe2loO5JO7P1nQ" key="proxy_username">
                <expression xmi:type="expression:Expression" xmi:id="_1Aeqbc5JEe2loO5JO7P1nQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_1Aeqbs5JEe2loO5JO7P1nQ" key="proxy_password">
                <expression xmi:type="expression:Expression" xmi:id="_1Aeqb85JEe2loO5JO7P1nQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_1AeqcM5JEe2loO5JO7P1nQ" key="socket_timeout_ms">
                <expression xmi:type="expression:Expression" xmi:id="_1Aeqcc5JEe2loO5JO7P1nQ" name="60000" content="60000" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_1Aeqcs5JEe2loO5JO7P1nQ" key="connection_timeout_ms">
                <expression xmi:type="expression:Expression" xmi:id="_1Aeqc85JEe2loO5JO7P1nQ" name="60000" content="60000" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_1AeqdM5JEe2loO5JO7P1nQ" key="trust_strategy">
                <expression xmi:type="expression:Expression" xmi:id="_1AfRUM5JEe2loO5JO7P1nQ" name="TRUST_ALL" content="TRUST_ALL" returnTypeFixed="true"/>
              </parameters>
            </configuration>
            <outputs xmi:type="expression:Operation" xmi:id="_1AfRUc5JEe2loO5JO7P1nQ">
              <leftOperand xmi:type="expression:Expression" xmi:id="_1AfRUs5JEe2loO5JO7P1nQ" name="currentTotem" content="currentTotem" type="TYPE_VARIABLE" returnType="com.skymed.totem.model.Totem">
                <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_1AfRU85JEe2loO5JO7P1nQ" name="currentTotem" dataType="_eA_0BsziEe22052-PBnc4Q" className="com.skymed.totem.model.Totem"/>
              </leftOperand>
              <rightOperand xmi:type="expression:Expression" xmi:id="_1AfRVM5JEe2loO5JO7P1nQ" name="getCurrentTotem()" content="import static com.fasterxml.jackson.databind.DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES&#xD;&#xA;&#xD;&#xA;import com.fasterxml.jackson.databind.json.JsonMapper&#xD;&#xA;import com.skymed.totem.model.Totem&#xD;&#xA;&#xD;&#xA;def objectMapper = JsonMapper.builder().configure(FAIL_ON_UNKNOWN_PROPERTIES, false).build();&#xD;&#xA;if (status_code == 200) {&#xD;&#xA;&#x9;return objectMapper.readValue(bodyAsString, Totem.class)&#xD;&#xA;} &#xD;&#xA;return null&#xD;&#xA;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="com.skymed.totem.model.Totem">
                <referencedElements xmi:type="definition:Output" xmi:id="_faVmQM5fEe2loO5JO7P1nQ" name="status_code" type="java.lang.Integer"/>
                <referencedElements xmi:type="definition:Output" xmi:id="_faVmQc5fEe2loO5JO7P1nQ" name="bodyAsString" type="java.lang.String"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_1AfRVs5JEe2loO5JO7P1nQ" type="CREATE_BUSINESS_DATA"/>
            </outputs>
          </connectors>
          <operations xmi:type="expression:Operation" xmi:id="_9Vc5sM5gEe2loO5JO7P1nQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_9Vc5sc5gEe2loO5JO7P1nQ" name="isValid" content="isValid" type="TYPE_VARIABLE" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:Data" xmi:id="_-FDKoM5gEe2loO5JO7P1nQ" name="isValid" dataType="_eA_z_sziEe22052-PBnc4Q"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_9Vc5ss5gEe2loO5JO7P1nQ" name="isValidTotem()" content="return currentTotem != null;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_Fv7LoM5hEe2loO5JO7P1nQ" name="currentTotem" dataType="_eA_0BsziEe22052-PBnc4Q" className="com.skymed.totem.model.Totem"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_9Vc5s85gEe2loO5JO7P1nQ" type="ASSIGNMENT"/>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_pZYz485gEe2loO5JO7P1nQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_pZYz5M5gEe2loO5JO7P1nQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_pZYz5c5gEe2loO5JO7P1nQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_pZYz585gEe2loO5JO7P1nQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_pZYz5s5gEe2loO5JO7P1nQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_ISDyYM57Ee2loO5JO7P1nQ" name="Mostrar listado de colas disponibles" outgoing="_x4ZCYM1hEe2_GaC9xHNsqQ" incoming="_nRO6EMzrEe22052-PBnc4Q">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_nRLPsszrEe22052-PBnc4Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_nRLPsczrEe22052-PBnc4Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_nRLPs8zrEe22052-PBnc4Q" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_besvwM5iEe2loO5JO7P1nQ" name="getColasByTotem" definitionId="rest-get" event="ON_ENTER" definitionVersion="1.2.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_besvwc5iEe2loO5JO7P1nQ" definitionId="rest-get" version="1.2.0" modelVersion="7.12.0-004">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_besvws5iEe2loO5JO7P1nQ" key="url">
                <expression xmi:type="expression:Expression" xmi:id="_besvw85iEe2loO5JO7P1nQ" name="getColasByTotemUrl()" content="if (currentTotem != null) {&#xD;&#xA;&#x9;return 'https://testcrm-rest.skytel.com.ar:8443/admision/resources/totem-app/find-colas-by-totem/' + currentTotem.id&#xD;&#xA;} &#xD;&#xA;return 'https://testcrm-rest.skytel.com.ar:8443/admision/resources/totem-app/find-colas-by-totem/20'&#xD;&#xA;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_kE180M57Ee2loO5JO7P1nQ" name="currentTotem" dataType="_eA_0BsziEe22052-PBnc4Q" className="com.skymed.totem.model.Totem"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_besvxM5iEe2loO5JO7P1nQ" key="urlCookies">
                <expression xmi:type="expression:TableExpression" xmi:id="_besvxc5iEe2loO5JO7P1nQ"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_besvxs5iEe2loO5JO7P1nQ" key="urlHeaders">
                <expression xmi:type="expression:TableExpression" xmi:id="_besvx85iEe2loO5JO7P1nQ"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_besvyM5iEe2loO5JO7P1nQ" key="do_not_follow_redirect">
                <expression xmi:type="expression:Expression" xmi:id="_besvyc5iEe2loO5JO7P1nQ" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_besvys5iEe2loO5JO7P1nQ" key="ignore_body">
                <expression xmi:type="expression:Expression" xmi:id="_besvy85iEe2loO5JO7P1nQ" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_besvzM5iEe2loO5JO7P1nQ" key="TLS">
                <expression xmi:type="expression:Expression" xmi:id="_besvzc5iEe2loO5JO7P1nQ" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_besvzs5iEe2loO5JO7P1nQ" key="hostname_verifier">
                <expression xmi:type="expression:Expression" xmi:id="_besvz85iEe2loO5JO7P1nQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_besv0M5iEe2loO5JO7P1nQ" key="trust_store_file">
                <expression xmi:type="expression:Expression" xmi:id="_besv0c5iEe2loO5JO7P1nQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_besv0s5iEe2loO5JO7P1nQ" key="trust_store_password">
                <expression xmi:type="expression:Expression" xmi:id="_besv085iEe2loO5JO7P1nQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_besv1M5iEe2loO5JO7P1nQ" key="key_store_file">
                <expression xmi:type="expression:Expression" xmi:id="_besv1c5iEe2loO5JO7P1nQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_besv1s5iEe2loO5JO7P1nQ" key="key_store_password">
                <expression xmi:type="expression:Expression" xmi:id="_besv185iEe2loO5JO7P1nQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_besv2M5iEe2loO5JO7P1nQ" key="auth_type">
                <expression xmi:type="expression:Expression" xmi:id="_besv2c5iEe2loO5JO7P1nQ" name="NONE" content="NONE" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_besv2s5iEe2loO5JO7P1nQ" key="auth_username">
                <expression xmi:type="expression:Expression" xmi:id="_besv285iEe2loO5JO7P1nQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_besv3M5iEe2loO5JO7P1nQ" key="auth_password">
                <expression xmi:type="expression:Expression" xmi:id="_besv3c5iEe2loO5JO7P1nQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_besv3s5iEe2loO5JO7P1nQ" key="auth_host">
                <expression xmi:type="expression:Expression" xmi:id="_besv385iEe2loO5JO7P1nQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_besv4M5iEe2loO5JO7P1nQ" key="auth_port">
                <expression xmi:type="expression:Expression" xmi:id="_besv4c5iEe2loO5JO7P1nQ" name="-1" content="-1" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_besv4s5iEe2loO5JO7P1nQ" key="auth_realm">
                <expression xmi:type="expression:Expression" xmi:id="_besv485iEe2loO5JO7P1nQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_besv5M5iEe2loO5JO7P1nQ" key="auth_preemptive">
                <expression xmi:type="expression:Expression" xmi:id="_besv5c5iEe2loO5JO7P1nQ" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_besv5s5iEe2loO5JO7P1nQ" key="proxy_protocol">
                <expression xmi:type="expression:Expression" xmi:id="_besv585iEe2loO5JO7P1nQ" name="HTTP" content="HTTP" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_besv6M5iEe2loO5JO7P1nQ" key="proxy_host">
                <expression xmi:type="expression:Expression" xmi:id="_besv6c5iEe2loO5JO7P1nQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_besv6s5iEe2loO5JO7P1nQ" key="proxy_port">
                <expression xmi:type="expression:Expression" xmi:id="_besv685iEe2loO5JO7P1nQ" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_besv7M5iEe2loO5JO7P1nQ" key="proxy_username">
                <expression xmi:type="expression:Expression" xmi:id="_besv7c5iEe2loO5JO7P1nQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_besv7s5iEe2loO5JO7P1nQ" key="proxy_password">
                <expression xmi:type="expression:Expression" xmi:id="_besv785iEe2loO5JO7P1nQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_besv8M5iEe2loO5JO7P1nQ" key="socket_timeout_ms">
                <expression xmi:type="expression:Expression" xmi:id="_besv8c5iEe2loO5JO7P1nQ" name="60000" content="60000" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_besv8s5iEe2loO5JO7P1nQ" key="connection_timeout_ms">
                <expression xmi:type="expression:Expression" xmi:id="_besv885iEe2loO5JO7P1nQ" name="60000" content="60000" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_besv9M5iEe2loO5JO7P1nQ" key="trust_strategy">
                <expression xmi:type="expression:Expression" xmi:id="_besv9c5iEe2loO5JO7P1nQ" name="TRUST_ALL" content="TRUST_ALL" returnTypeFixed="true"/>
              </parameters>
            </configuration>
            <outputs xmi:type="expression:Operation" xmi:id="_besv9s5iEe2loO5JO7P1nQ">
              <leftOperand xmi:type="expression:Expression" xmi:id="_besv985iEe2loO5JO7P1nQ" name="colasDisponibles" content="colasDisponibles" type="TYPE_VARIABLE" returnType="java.util.List">
                <referencedElements xmi:type="process:JavaObjectData" xmi:id="_5AZBIM5kEe2loO5JO7P1nQ" documentation="Listado de colas Disponibles" name="colasDisponibles" dataType="_eA_0BMziEe22052-PBnc4Q" className="java.util.List"/>
              </leftOperand>
              <rightOperand xmi:type="expression:Expression" xmi:id="_besv-c5iEe2loO5JO7P1nQ" name="getCurrentTotem()" content="import static com.fasterxml.jackson.databind.DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES&#xD;&#xA;&#xD;&#xA;import com.fasterxml.jackson.databind.json.JsonMapper&#xD;&#xA;import java.util.List&#xD;&#xA;&#xD;&#xA;def objectMapper = JsonMapper.builder().configure(FAIL_ON_UNKNOWN_PROPERTIES, false).build();&#xD;&#xA;if (status_code == 200) {&#xD;&#xA;&#x9;return objectMapper.readValue(bodyAsString, List.class)&#xD;&#xA;}&#xD;&#xA;return null" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.util.List">
                <referencedElements xmi:type="definition:Output" xmi:id="_6ujxIM56Ee2loO5JO7P1nQ" name="bodyAsString" type="java.lang.String"/>
                <referencedElements xmi:type="definition:Output" xmi:id="_6ujxIc56Ee2loO5JO7P1nQ" name="status_code" type="java.lang.Integer"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_besv-85iEe2loO5JO7P1nQ" type="ASSIGNMENT"/>
            </outputs>
          </connectors>
          <loopCondition xmi:type="expression:Expression" xmi:id="_nRLPtMzrEe22052-PBnc4Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_nRLPtczrEe22052-PBnc4Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_nRLPtszrEe22052-PBnc4Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_nRLPuMzrEe22052-PBnc4Q" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_nRLPt8zrEe22052-PBnc4Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_bpJHgMzpEe22052-PBnc4Q" name="Paciente" actor="_N73z4M1lEe2_GaC9xHNsqQ">
        <elements xmi:type="process:Task" xmi:id="_bZ3DcMzrEe22052-PBnc4Q" name="Presionar la pantalla" outgoing="_nRO6EMzrEe22052-PBnc4Q" incoming="_44t4MM4qEe2v9Z4_FCyumw" actor="_N73z4M1lEe2_GaC9xHNsqQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_bZ3DcszrEe22052-PBnc4Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_bZ3DcczrEe22052-PBnc4Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_bZ3Dc8zrEe22052-PBnc4Q" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_bZ3DdMzrEe22052-PBnc4Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_bZ3qgMzrEe22052-PBnc4Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_bZ3qgczrEe22052-PBnc4Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_bZ3qg8zrEe22052-PBnc4Q" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_bZ3qgszrEe22052-PBnc4Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_bZ3qhczrEe22052-PBnc4Q" url="">
            <targetForm xmi:type="expression:Expression" xmi:id="_9t07IM1oEe2_GaC9xHNsqQ" name="welcome" content="80219ca0-0693-4da4-8781-0b8d8c513031" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_bZ3qhMzrEe22052-PBnc4Q"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_bZ3qh8zrEe22052-PBnc4Q" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_teBv4M1hEe2_GaC9xHNsqQ" name="Selecciona cola" outgoing="_s4RiAM1iEe2_GaC9xHNsqQ" incoming="_x4ZCYM1hEe2_GaC9xHNsqQ" actor="_N73z4M1lEe2_GaC9xHNsqQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_teOkMc1hEe2_GaC9xHNsqQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_teOkMM1hEe2_GaC9xHNsqQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_teOkMs1hEe2_GaC9xHNsqQ" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_thiwgM5qEe2loO5JO7P1nQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_thiwgc5qEe2loO5JO7P1nQ" name="selectedCola" content="selectedCola" type="TYPE_VARIABLE" returnType="com.skymed.totem.model.ColaAdmision">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_thiwgs5qEe2loO5JO7P1nQ" name="selectedCola" dataType="_eA_0BsziEe22052-PBnc4Q" className="com.skymed.totem.model.ColaAdmision"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_thiwg85qEe2loO5JO7P1nQ" name="selectedColaInput.id" content="selectedColaInput?.id?.trim() ? selectedColaInput.id.toLong() : null" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Long">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_thiwhM5qEe2loO5JO7P1nQ" name="selectedColaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_thiwhc5qEe2loO5JO7P1nQ" type="JAVA_METHOD" expression="setId">
              <inputTypes>java.lang.Long</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_teOkM81hEe2_GaC9xHNsqQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_tePLQM1hEe2_GaC9xHNsqQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_tePLQc1hEe2_GaC9xHNsqQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_tePLQ81hEe2_GaC9xHNsqQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_tePLQs1hEe2_GaC9xHNsqQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_tePLRc1hEe2_GaC9xHNsqQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_7psyIc1mEe2_GaC9xHNsqQ" name="seleccionarCola" content="e85167c7-d5f0-472f-90ca-8ee207f4f858" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_tePLRM1hEe2_GaC9xHNsqQ">
            <inputs xmi:type="process:ContractInput" xmi:id="_thiJcM5qEe2loO5JO7P1nQ" name="selectedColaInput" type="COMPLEX" dataReference="selectedCola" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_thiJcc5qEe2loO5JO7P1nQ" name="id" createMode="false"/>
            </inputs>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_thiJcs5qEe2loO5JO7P1nQ" expression="selectedColaInput?.id != null" errorMessage="id is mandatory for ColaAdmision" name="mandatory_selectedColaInput_id">
              <inputNames>selectedColaInput</inputNames>
            </constraints>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_thiJc85qEe2loO5JO7P1nQ" expression="!selectedColaInput?.id || selectedColaInput?.id.isLong()" errorMessage="A Long value is expected for ColaAdmision.id" name="type_long_selectedColaInput_id">
              <inputNames>selectedColaInput</inputNames>
            </constraints>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_tePLR81hEe2_GaC9xHNsqQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_SDIc0M1oEe2_GaC9xHNsqQ" name="Seleccion de Prioridades" outgoing="_Swi8cM1oEe2_GaC9xHNsqQ" incoming="_QL_8EM1oEe2_GaC9xHNsqQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_QL51cs1oEe2_GaC9xHNsqQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_QL51cc1oEe2_GaC9xHNsqQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_QL51c81oEe2_GaC9xHNsqQ" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_H2OkRM52Ee2loO5JO7P1nQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_H2OkRc52Ee2loO5JO7P1nQ" name="selectedPrioridad" content="selectedPrioridad" type="TYPE_VARIABLE" returnType="com.skymed.totem.model.Prioridad">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_H2OkRs52Ee2loO5JO7P1nQ" name="selectedPrioridad" dataType="_eA_0BsziEe22052-PBnc4Q" className="com.skymed.totem.model.Prioridad"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_H2OkR852Ee2loO5JO7P1nQ" name="selectedPrioridadInput.id" content="selectedPrioridadInput?.id?.trim() ? selectedPrioridadInput.id.toLong() : null" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Long">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_H2OkSM52Ee2loO5JO7P1nQ" name="selectedPrioridadInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_H2OkSc52Ee2loO5JO7P1nQ" type="JAVA_METHOD" expression="setId">
              <inputTypes>java.lang.Long</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_QL51dM1oEe2_GaC9xHNsqQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_QL51dc1oEe2_GaC9xHNsqQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_QL51ds1oEe2_GaC9xHNsqQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_QL51eM1oEe2_GaC9xHNsqQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_QL51d81oEe2_GaC9xHNsqQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_SDIc2s1oEe2_GaC9xHNsqQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_Mxse8M2VEe2r5bmlX6-2kg" name="seleccionarPrioridad" content="3d543c28-ece8-4e88-b559-70adff14f9e4" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_SDIc2c1oEe2_GaC9xHNsqQ">
            <inputs xmi:type="process:ContractInput" xmi:id="_H2OkQM52Ee2loO5JO7P1nQ" name="selectedPrioridadInput" type="COMPLEX" dataReference="selectedPrioridad" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_H2OkQc52Ee2loO5JO7P1nQ" name="id" createMode="false"/>
            </inputs>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_H2OkQs52Ee2loO5JO7P1nQ" expression="selectedPrioridadInput?.id != null" errorMessage="id is mandatory for Prioridad" name="mandatory_selectedPrioridadInput_id">
              <inputNames>selectedPrioridadInput</inputNames>
            </constraints>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_H2OkQ852Ee2loO5JO7P1nQ" expression="!selectedPrioridadInput?.id || selectedPrioridadInput?.id.isLong()" errorMessage="A Long value is expected for Prioridad.id" name="type_long_selectedPrioridadInput_id">
              <inputNames>selectedPrioridadInput</inputNames>
            </constraints>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_SDIc3M1oEe2_GaC9xHNsqQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <data xmi:type="process:Data" xmi:id="_X8CuMMzqEe22052-PBnc4Q" name="isValid" dataType="_eA_z_sziEe22052-PBnc4Q">
        <defaultValue xmi:type="expression:Expression" xmi:id="_X8CuMczqEe22052-PBnc4Q" name="true" content="true" returnType="java.lang.Boolean"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_Ep-z8M10Ee2_GaC9xHNsqQ" documentation="Direccion IP del cliente" name="ipAddress" dataType="_eA_0A8ziEe22052-PBnc4Q">
        <defaultValue xmi:type="expression:Expression" xmi:id="_Ep-z8c10Ee2_GaC9xHNsqQ" content=""/>
      </data>
      <data xmi:type="process:BusinessObjectData" xmi:id="_55TpMM1_Ee2_GaC9xHNsqQ" name="currentTotem" dataType="_eA_0BsziEe22052-PBnc4Q" className="com.skymed.totem.model.Totem">
        <defaultValue xmi:type="expression:Expression" xmi:id="_55TpMc1_Ee2_GaC9xHNsqQ" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <data xmi:type="process:BusinessObjectData" xmi:id="_pxPHoM5qEe2loO5JO7P1nQ" name="selectedCola" dataType="_eA_0BsziEe22052-PBnc4Q" className="com.skymed.totem.model.ColaAdmision">
        <defaultValue xmi:type="expression:Expression" xmi:id="_pxPHoc5qEe2loO5JO7P1nQ" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <data xmi:type="process:BusinessObjectData" xmi:id="_0mn70M51Ee2loO5JO7P1nQ" name="selectedPrioridad" dataType="_eA_0BsziEe22052-PBnc4Q" className="com.skymed.totem.model.Prioridad">
        <defaultValue xmi:type="expression:Expression" xmi:id="_0mn70c51Ee2loO5JO7P1nQ" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <data xmi:type="process:JavaObjectData" xmi:id="_1wIIQM56Ee2loO5JO7P1nQ" name="colasDisponibles" dataType="_eA_0BMziEe22052-PBnc4Q" className="java.util.List">
        <defaultValue xmi:type="expression:Expression" xmi:id="_1wIIQc56Ee2loO5JO7P1nQ" content="" type="TYPE_READ_ONLY_SCRIPT" returnType="java.util.List"/>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_eA_z5sziEe22052-PBnc4Q" type="NONE" url="">
        <targetForm xmi:type="expression:Expression" xmi:id="_bJNXEM2VEe2r5bmlX6-2kg" name="home" content="0bbf0f7c-1f3c-417b-b12d-1da7cd1a513f" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_eA_z6MziEe22052-PBnc4Q" type="NONE">
        <targetForm xmi:type="expression:Expression" xmi:id="_eA_z6cziEe22052-PBnc4Q" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_FxEykMzqEe22052-PBnc4Q" name="NO" target="_BVeCEM4rEe2v9Z4_FCyumw" source="_gyqeQM1mEe2_GaC9xHNsqQ" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_FxEykczqEe22052-PBnc4Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_FxEykszqEe22052-PBnc4Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_nRO6EMzrEe22052-PBnc4Q" target="_ISDyYM57Ee2loO5JO7P1nQ" source="_bZ3DcMzrEe22052-PBnc4Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_nRO6EczrEe22052-PBnc4Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_nRO6EszrEe22052-PBnc4Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_x4ZCYM1hEe2_GaC9xHNsqQ" target="_teBv4M1hEe2_GaC9xHNsqQ" source="_ISDyYM57Ee2loO5JO7P1nQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_x4ZpcM1hEe2_GaC9xHNsqQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_x4Zpcc1hEe2_GaC9xHNsqQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_s4RiAM1iEe2_GaC9xHNsqQ" target="_EoYEsM1kEe2_GaC9xHNsqQ" source="_teBv4M1hEe2_GaC9xHNsqQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_s4RiAc1iEe2_GaC9xHNsqQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_s4RiAs1iEe2_GaC9xHNsqQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_wP9aEM1jEe2_GaC9xHNsqQ" target="_ICNuUM1kEe2_GaC9xHNsqQ" source="_HPeCwM1kEe2_GaC9xHNsqQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_wP9aEc1jEe2_GaC9xHNsqQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_wP9aEs1jEe2_GaC9xHNsqQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_JYF8IM1kEe2_GaC9xHNsqQ" target="_M9O20M1kEe2_GaC9xHNsqQ" source="_ICNuUM1kEe2_GaC9xHNsqQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_JYF8Ic1kEe2_GaC9xHNsqQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_JYF8Is1kEe2_GaC9xHNsqQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_SQOacM1kEe2_GaC9xHNsqQ" target="_PL5t0M1kEe2_GaC9xHNsqQ" source="_M9O20M1kEe2_GaC9xHNsqQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_SQPBgM1kEe2_GaC9xHNsqQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_SQPBgc1kEe2_GaC9xHNsqQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_jTIh0M1kEe2_GaC9xHNsqQ" target="_ho-tIM1kEe2_GaC9xHNsqQ" source="_PL5t0M1kEe2_GaC9xHNsqQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_jTIh0c1kEe2_GaC9xHNsqQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_jTIh0s1kEe2_GaC9xHNsqQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_mthlEM1kEe2_GaC9xHNsqQ" target="_ho-tIM1kEe2_GaC9xHNsqQ" source="_BVeCEM4rEe2v9Z4_FCyumw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_mthlEc1kEe2_GaC9xHNsqQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_mthlEs1kEe2_GaC9xHNsqQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_QL_8EM1oEe2_GaC9xHNsqQ" target="_SDIc0M1oEe2_GaC9xHNsqQ" source="_EoYEsM1kEe2_GaC9xHNsqQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_QL_8Ec1oEe2_GaC9xHNsqQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_QL_8Es1oEe2_GaC9xHNsqQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Swi8cM1oEe2_GaC9xHNsqQ" target="_HPeCwM1kEe2_GaC9xHNsqQ" source="_SDIc0M1oEe2_GaC9xHNsqQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Swi8cc1oEe2_GaC9xHNsqQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_Swi8cs1oEe2_GaC9xHNsqQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_4S-T0M2bEe2r5bmlX6-2kg" target="_pZYM0M5gEe2loO5JO7P1nQ" source="_eA-lw8ziEe22052-PBnc4Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_4S_h8M2bEe2r5bmlX6-2kg"/>
        <condition xmi:type="expression:Expression" xmi:id="_4S_h8c2bEe2r5bmlX6-2kg" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_44t4MM4qEe2v9Z4_FCyumw" target="_bZ3DcMzrEe22052-PBnc4Q" source="_gyqeQM1mEe2_GaC9xHNsqQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_44ywsM4qEe2v9Z4_FCyumw"/>
        <condition xmi:type="expression:Expression" xmi:id="_44zXwM4qEe2v9Z4_FCyumw" name="isValid" content="isValid" type="TYPE_VARIABLE" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="_75e6gM4qEe2v9Z4_FCyumw" name="isValid" dataType="_eA_z_sziEe22052-PBnc4Q"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_pZp5oM5gEe2loO5JO7P1nQ" target="_gyqeQM1mEe2_GaC9xHNsqQ" source="_pZYM0M5gEe2loO5JO7P1nQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_pZp5oc5gEe2loO5JO7P1nQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_pZp5os5gEe2loO5JO7P1nQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_eA_z7cziEe22052-PBnc4Q" documentation="Este es un ejemplo de actor que está mapeado a cualquier usuario de la organización ACME" name="Employee actor"/>
      <actors xmi:type="process:Actor" xmi:id="_N73z4M1lEe2_GaC9xHNsqQ" name="Paciente" initiator="true"/>
      <configurations xmi:type="configuration:Configuration" xmi:id="_-9MjkM2wEe2r5bmlX6-2kg" name="Production" version="7.12.0-004" username="walter.bates">
        <actorMappings xmi:type="actormapping:ActorMappingsType" xmi:id="_-9Mjms2wEe2r5bmlX6-2kg">
          <actorMapping xmi:type="actormapping:ActorMapping" xmi:id="_-9Mjm82wEe2r5bmlX6-2kg" name="Employee actor">
            <groups xmi:type="actormapping:Groups" xmi:id="_-9MjnM2wEe2r5bmlX6-2kg">
              <group>/acme</group>
            </groups>
            <memberships xmi:type="actormapping:Membership" xmi:id="_-9Mjnc2wEe2r5bmlX6-2kg"/>
            <roles xmi:type="actormapping:Roles" xmi:id="_-9Mjns2wEe2r5bmlX6-2kg"/>
            <users xmi:type="actormapping:Users" xmi:id="_-9Mjn82wEe2r5bmlX6-2kg"/>
          </actorMapping>
          <actorMapping xmi:type="actormapping:ActorMapping" xmi:id="_-9MjoM2wEe2r5bmlX6-2kg" name="Paciente">
            <groups xmi:type="actormapping:Groups" xmi:id="_-9Mjoc2wEe2r5bmlX6-2kg">
              <group>/acme</group>
            </groups>
            <memberships xmi:type="actormapping:Membership" xmi:id="_-9Mjos2wEe2r5bmlX6-2kg"/>
            <roles xmi:type="actormapping:Roles" xmi:id="_-9Mjo82wEe2r5bmlX6-2kg"/>
            <users xmi:type="actormapping:Users" xmi:id="_-9MjpM2wEe2r5bmlX6-2kg"/>
          </actorMapping>
        </actorMappings>
        <definitionMappings xmi:type="configuration:DefinitionMapping" xmi:id="__gDngM5JEe2loO5JO7P1nQ" type="CONNECTOR" definitionId="rest-get" definitionVersion="1.2.0" implementationId="rest-get-impl" implementationVersion="1.3.1"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_-9Mjks2wEe2r5bmlX6-2kg" id="CONNECTOR">
          <children xmi:type="configuration:FragmentContainer" xmi:id="__lqgQM5JEe2loO5JO7P1nQ" id="rest-get-impl-1.3.1">
            <fragments xmi:type="configuration:Fragment" xmi:id="__ltjkM5JEe2loO5JO7P1nQ" key="rest-get-impl -- 1.3.1" value="bonita-connector-rest-1.3.1.jar" type="CONNECTOR"/>
          </children>
        </processDependencies>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_-9Mjlc2wEe2r5bmlX6-2kg" id="GROOVY_SCRIPT"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_-9Mjls2wEe2r5bmlX6-2kg" id="ACTOR_FILTER"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_-9Mjl82wEe2r5bmlX6-2kg" id="OTHER"/>
        <applicationDependencies xmi:type="configuration:FragmentContainer" xmi:id="_-9MjmM2wEe2r5bmlX6-2kg" id="GROOVY_SCRIPT"/>
        <applicationDependencies xmi:type="configuration:FragmentContainer" xmi:id="_-9Mjmc2wEe2r5bmlX6-2kg" id="OTHER"/>
      </configurations>
      <contract xmi:type="process:Contract" xmi:id="_eA_z7sziEe22052-PBnc4Q"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_eA_z78ziEe22052-PBnc4Q">
        <name xmi:type="expression:Expression" xmi:id="_eA_z8MziEe22052-PBnc4Q" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_eA_z8cziEe22052-PBnc4Q" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_eA_z8sziEe22052-PBnc4Q">
        <name xmi:type="expression:Expression" xmi:id="_eA_z88ziEe22052-PBnc4Q" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_eA_z9MziEe22052-PBnc4Q" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_eA_z9cziEe22052-PBnc4Q">
        <name xmi:type="expression:Expression" xmi:id="_eA_z9sziEe22052-PBnc4Q" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_eA_z98ziEe22052-PBnc4Q" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_eA_z-MziEe22052-PBnc4Q">
        <name xmi:type="expression:Expression" xmi:id="_eA_z-cziEe22052-PBnc4Q" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_eA_z-sziEe22052-PBnc4Q" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_eA_z-8ziEe22052-PBnc4Q">
        <name xmi:type="expression:Expression" xmi:id="_eA_z_MziEe22052-PBnc4Q" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_eA_z_cziEe22052-PBnc4Q" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_eA_z_sziEe22052-PBnc4Q" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_eA_z_8ziEe22052-PBnc4Q" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_eA_0AMziEe22052-PBnc4Q" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_eA_0AcziEe22052-PBnc4Q" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_eA_0AsziEe22052-PBnc4Q" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_eA_0A8ziEe22052-PBnc4Q" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_eA_0BMziEe22052-PBnc4Q" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_eA_0BcziEe22052-PBnc4Q" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_eA_0BsziEe22052-PBnc4Q" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_eA_0B8ziEe22052-PBnc4Q" type="Process" element="_eA-lwMziEe22052-PBnc4Q" name="MiDiagrama" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_eA_0CMziEe22052-PBnc4Q" type="2007" element="_eA-lwcziEe22052-PBnc4Q">
      <children xmi:type="notation:DecorationNode" xmi:id="_eA_0CcziEe22052-PBnc4Q" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_eA_0CsziEe22052-PBnc4Q" type="7001">
        <children xmi:type="notation:Node" xmi:id="_eA_0C8ziEe22052-PBnc4Q" type="3007" element="_eA-lwsziEe22052-PBnc4Q">
          <children xmi:type="notation:DecorationNode" xmi:id="_eA_0DMziEe22052-PBnc4Q" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_eA_0DcziEe22052-PBnc4Q" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_eA_0EcziEe22052-PBnc4Q" type="3002" element="_eA-lw8ziEe22052-PBnc4Q" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_eA_0EsziEe22052-PBnc4Q" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_eA_0E8ziEe22052-PBnc4Q" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_eA_0FMziEe22052-PBnc4Q" x="62" y="205"/>
            </children>
            <children xmi:type="notation:Node" xmi:id="_1g2FUMzpEe22052-PBnc4Q" type="3015" element="_1g1eQMzpEe22052-PBnc4Q">
              <children xmi:type="notation:DecorationNode" xmi:id="_1g2FVczpEe22052-PBnc4Q" type="5010"/>
              <styles xmi:type="notation:DescriptionStyle" xmi:id="_1g2FUczpEe22052-PBnc4Q"/>
              <styles xmi:type="notation:FontStyle" xmi:id="_1g2FUszpEe22052-PBnc4Q" fontName="Segoe UI"/>
              <styles xmi:type="notation:LineStyle" xmi:id="_1g2FU8zpEe22052-PBnc4Q"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_1g2FVMzpEe22052-PBnc4Q" x="53" y="90" width="188"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_EoYryM1kEe2_GaC9xHNsqQ" type="3006" element="_EoYEsM1kEe2_GaC9xHNsqQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_EoZS0M1kEe2_GaC9xHNsqQ" type="5006"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_EoYryc1kEe2_GaC9xHNsqQ" x="902" y="181" width="158" height="78"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_HPep2M1kEe2_GaC9xHNsqQ" type="3006" element="_HPeCwM1kEe2_GaC9xHNsqQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_HPfQ4M1kEe2_GaC9xHNsqQ" type="5006"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_HPep2c1kEe2_GaC9xHNsqQ" x="1118" y="182" width="152" height="76"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ICOVaM1kEe2_GaC9xHNsqQ" type="3006" element="_ICNuUM1kEe2_GaC9xHNsqQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_ICOVas1kEe2_GaC9xHNsqQ" type="5006"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ICOVac1kEe2_GaC9xHNsqQ" x="1368" y="182" width="150" height="75"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_M9Pd4M1kEe2_GaC9xHNsqQ" type="3006" element="_M9O20M1kEe2_GaC9xHNsqQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_M9Pd4s1kEe2_GaC9xHNsqQ" type="5006"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_M9Pd4c1kEe2_GaC9xHNsqQ" x="1622" y="180" width="160" height="80"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_PMTWcM1kEe2_GaC9xHNsqQ" type="3017" element="_PL5t0M1kEe2_GaC9xHNsqQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_PMTWcs1kEe2_GaC9xHNsqQ" type="5032">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_PMTWc81kEe2_GaC9xHNsqQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_PMTWcc1kEe2_GaC9xHNsqQ" x="1838" y="205"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ho_7QM1kEe2_GaC9xHNsqQ" type="3062" element="_ho-tIM1kEe2_GaC9xHNsqQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_ho_7Qs1kEe2_GaC9xHNsqQ" type="5090">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_ho_7Q81kEe2_GaC9xHNsqQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ho_7Qc1kEe2_GaC9xHNsqQ" x="1982" y="205"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_gyrFUs1mEe2_GaC9xHNsqQ" type="3008" element="_gyqeQM1mEe2_GaC9xHNsqQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_gyrFVM1mEe2_GaC9xHNsqQ" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_gyrFVc1mEe2_GaC9xHNsqQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_gyrFU81mEe2_GaC9xHNsqQ" x="326" y="198" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_BVhscM4rEe2v9Z4_FCyumw" type="3005" element="_BVeCEM4rEe2v9Z4_FCyumw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_BViTgM4rEe2v9Z4_FCyumw" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_BVhscc4rEe2v9Z4_FCyumw" x="494" y="73" width="168" height="84"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_pZZa8M5gEe2loO5JO7P1nQ" type="3027" element="_pZYM0M5gEe2loO5JO7P1nQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_pZZa8s5gEe2loO5JO7P1nQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_pZZa8c5gEe2loO5JO7P1nQ" x="158" y="195"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ISEZeM57Ee2loO5JO7P1nQ" type="3027" element="_ISDyYM57Ee2loO5JO7P1nQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_ISFAgM57Ee2loO5JO7P1nQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ISEZec57Ee2loO5JO7P1nQ" x="686" y="181" width="154" height="77"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_eA_0FcziEe22052-PBnc4Q"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_eA_0FsziEe22052-PBnc4Q" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_eA_0F8ziEe22052-PBnc4Q"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_eA_0GMziEe22052-PBnc4Q"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_eA_0GcziEe22052-PBnc4Q" x="53" y="10" width="2192" height="500"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_bpJukMzpEe22052-PBnc4Q" type="3007" element="_bpJHgMzpEe22052-PBnc4Q">
          <children xmi:type="notation:DecorationNode" xmi:id="_bpJulczpEe22052-PBnc4Q" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_bpJulszpEe22052-PBnc4Q" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_bZ4RkMzrEe22052-PBnc4Q" type="3005" element="_bZ3DcMzrEe22052-PBnc4Q" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_bZ4RkszrEe22052-PBnc4Q" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_bZ4RkczrEe22052-PBnc4Q" x="494" y="93" width="176" height="88"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_tfIjIM1hEe2_GaC9xHNsqQ" type="3005" element="_teBv4M1hEe2_GaC9xHNsqQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_tfJKMM1hEe2_GaC9xHNsqQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_tfIjIc1hEe2_GaC9xHNsqQ" x="806" y="89" width="190" height="95"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_SDJD4M1oEe2_GaC9xHNsqQ" type="3005" element="_SDIc0M1oEe2_GaC9xHNsqQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_SDJD4s1oEe2_GaC9xHNsqQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_SDJD4c1oEe2_GaC9xHNsqQ" x="1084" y="91" width="185" height="92"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_bpJukczpEe22052-PBnc4Q"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_bpJukszpEe22052-PBnc4Q" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_bpJuk8zpEe22052-PBnc4Q"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_bpJul8zpEe22052-PBnc4Q"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_bpJulMzpEe22052-PBnc4Q" x="53" y="250" width="1292" height="273"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_eA_0GsziEe22052-PBnc4Q"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_eA_0G8ziEe22052-PBnc4Q" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_eA_0HMziEe22052-PBnc4Q"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_eA_0HcziEe22052-PBnc4Q"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_eA_0HsziEe22052-PBnc4Q" width="2220" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_eA_0H8ziEe22052-PBnc4Q"/>
    <edges xmi:type="notation:Connector" xmi:id="_FxEyk8zqEe22052-PBnc4Q" type="4001" element="_FxEykMzqEe22052-PBnc4Q" source="_gyrFUs1mEe2_GaC9xHNsqQ" target="_BVhscM4rEe2v9Z4_FCyumw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_FxFZoMzqEe22052-PBnc4Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_FxFZoczqEe22052-PBnc4Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_FxEylMzqEe22052-PBnc4Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_FxEylczqEe22052-PBnc4Q" points="[-10, -16, -131, 106]$[29, -16, -92, 106]$[29, -106, -92, 16]$[101, -106, -20, 16]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_FxGAsMzqEe22052-PBnc4Q" id="(1.0,0.6511627906976745)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_FxGAsczqEe22052-PBnc4Q" id="(0.12,0.38)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_nRO6E8zrEe22052-PBnc4Q" type="4001" element="_nRO6EMzrEe22052-PBnc4Q" source="_bZ4RkMzrEe22052-PBnc4Q" target="_ISEZeM57Ee2loO5JO7P1nQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_nRO6FszrEe22052-PBnc4Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_nRO6F8zrEe22052-PBnc4Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_nRO6FMzrEe22052-PBnc4Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_nRO6FczrEe22052-PBnc4Q" points="[18, -44, -163, 374]$[18, -187, -163, 231]$[152, -187, -29, 231]$[152, -379, -29, 39]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_x4beoM1hEe2_GaC9xHNsqQ" type="4001" element="_x4ZCYM1hEe2_GaC9xHNsqQ" source="_ISEZeM57Ee2loO5JO7P1nQ" target="_tfIjIM1hEe2_GaC9xHNsqQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_x4beo81hEe2_GaC9xHNsqQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_x4bepM1hEe2_GaC9xHNsqQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_x4beoc1hEe2_GaC9xHNsqQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_x4beos1hEe2_GaC9xHNsqQ" points="[-82, 47, -100, -272]$[-82, 191, -100, -128]$[14, 191, -4, -128]$[14, 307, -4, -12]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_x4dT0M1hEe2_GaC9xHNsqQ" id="(1.0,0.38961038961038963)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_x4dT0c1hEe2_GaC9xHNsqQ" id="(0.2736842105263158,0.12631578947368421)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_s4SJEM1iEe2_GaC9xHNsqQ" type="4001" element="_s4RiAM1iEe2_GaC9xHNsqQ" source="_tfIjIM1hEe2_GaC9xHNsqQ" target="_EoYryM1kEe2_GaC9xHNsqQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_s4SwIM1iEe2_GaC9xHNsqQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_s4SwIc1iEe2_GaC9xHNsqQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_s4SJEc1iEe2_GaC9xHNsqQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_s4SJEs1iEe2_GaC9xHNsqQ" points="[13, -13, -55, 298]$[13, -129, -55, 182]$[67, -129, -1, 182]$[67, -272, -1, 39]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_3eN_oM2nEe2r5bmlX6-2kg" id="(0.5631578947368421,0.1368421052631579)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_wP9aE81jEe2_GaC9xHNsqQ" type="4001" element="_wP9aEM1jEe2_GaC9xHNsqQ" source="_HPep2M1kEe2_GaC9xHNsqQ" target="_ICOVaM1kEe2_GaC9xHNsqQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_wP-BIM1jEe2_GaC9xHNsqQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_wP-BIc1jEe2_GaC9xHNsqQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_wP9aFM1jEe2_GaC9xHNsqQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_wP9aFc1jEe2_GaC9xHNsqQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_JYF8I81kEe2_GaC9xHNsqQ" type="4001" element="_JYF8IM1kEe2_GaC9xHNsqQ" source="_ICOVaM1kEe2_GaC9xHNsqQ" target="_M9Pd4M1kEe2_GaC9xHNsqQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_JYF8Js1kEe2_GaC9xHNsqQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_JYF8J81kEe2_GaC9xHNsqQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_JYF8JM1kEe2_GaC9xHNsqQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_JYF8Jc1kEe2_GaC9xHNsqQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_SQPokM1kEe2_GaC9xHNsqQ" type="4001" element="_SQOacM1kEe2_GaC9xHNsqQ" source="_M9Pd4M1kEe2_GaC9xHNsqQ" target="_PMTWcM1kEe2_GaC9xHNsqQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_SQPok81kEe2_GaC9xHNsqQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_SQPolM1kEe2_GaC9xHNsqQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_SQPokc1kEe2_GaC9xHNsqQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_SQPoks1kEe2_GaC9xHNsqQ" points="[0, 9, -90, -2]$[75, 9, -15, -2]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_SQQ2sM1kEe2_GaC9xHNsqQ" id="(1.0,0.3625)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_jTJI4M1kEe2_GaC9xHNsqQ" type="4001" element="_jTIh0M1kEe2_GaC9xHNsqQ" source="_PMTWcM1kEe2_GaC9xHNsqQ" target="_ho_7QM1kEe2_GaC9xHNsqQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_jTJI481kEe2_GaC9xHNsqQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_jTJI5M1kEe2_GaC9xHNsqQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_jTJI4c1kEe2_GaC9xHNsqQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_jTJI4s1kEe2_GaC9xHNsqQ" points="[0, -13, -112, 0]$[108, 1, -4, 14]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_jTJv8M1kEe2_GaC9xHNsqQ" id="(1.0,0.9333333333333333)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_mtiMIM1kEe2_GaC9xHNsqQ" type="4001" element="_mthlEM1kEe2_GaC9xHNsqQ" source="_BVhscM4rEe2v9Z4_FCyumw" target="_ho_7QM1kEe2_GaC9xHNsqQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_mtiMI81kEe2_GaC9xHNsqQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_mtiMJM1kEe2_GaC9xHNsqQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_mtiMIc1kEe2_GaC9xHNsqQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_mtiMIs1kEe2_GaC9xHNsqQ" points="[0, 8, -1337, -96]$[1334, 8, -3, -96]$[1334, 89, -3, -15]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_mtjaQM1kEe2_GaC9xHNsqQ" id="(1.0,0.39285714285714285)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_QL_8E81oEe2_GaC9xHNsqQ" type="4001" element="_QL_8EM1oEe2_GaC9xHNsqQ" source="_EoYryM1kEe2_GaC9xHNsqQ" target="_SDJD4M1oEe2_GaC9xHNsqQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_QMAjIM1oEe2_GaC9xHNsqQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_QMAjIc1oEe2_GaC9xHNsqQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_QL_8FM1oEe2_GaC9xHNsqQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_QL_8Fc1oEe2_GaC9xHNsqQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_SwkKkM1oEe2_GaC9xHNsqQ" type="4001" element="_Swi8cM1oEe2_GaC9xHNsqQ" source="_SDJD4M1oEe2_GaC9xHNsqQ" target="_HPep2M1kEe2_GaC9xHNsqQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_SwkKk81oEe2_GaC9xHNsqQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_SwkKlM1oEe2_GaC9xHNsqQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_SwkKkc1oEe2_GaC9xHNsqQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_SwkKks1oEe2_GaC9xHNsqQ" points="[-93, -32, -45, 277]$[-93, -164, -45, 145]$[-77, -164, -29, 145]$[-77, -296, -29, 13]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_SwlYsM1oEe2_GaC9xHNsqQ" id="(1.0,0.34782608695652173)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_SwlYsc1oEe2_GaC9xHNsqQ" id="(0.6842105263157895,0.8289473684210527)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_4TAJAM2bEe2r5bmlX6-2kg" type="4001" element="_4S-T0M2bEe2r5bmlX6-2kg" source="_eA_0EcziEe22052-PBnc4Q" target="_pZZa8M5gEe2loO5JO7P1nQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_4TAJA82bEe2r5bmlX6-2kg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_4TAJBM2bEe2r5bmlX6-2kg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_4TAJAc2bEe2r5bmlX6-2kg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_4TAJAs2bEe2r5bmlX6-2kg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_4TBXIM2bEe2r5bmlX6-2kg" id="(1.0,1.0)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_45Z0sM4qEe2v9Z4_FCyumw" type="4001" element="_44t4MM4qEe2v9Z4_FCyumw" source="_gyrFUs1mEe2_GaC9xHNsqQ" target="_bZ4RkMzrEe22052-PBnc4Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_45abwM4qEe2v9Z4_FCyumw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_45abwc4qEe2v9Z4_FCyumw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_45Z0sc4qEe2v9Z4_FCyumw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_45Z0ss4qEe2v9Z4_FCyumw" points="[-4, -4, -338, -378]$[335, 367, 1, -7]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_45dfEM4qEe2v9Z4_FCyumw" id="(1.0,0.6511627906976745)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_45dfEc4qEe2v9Z4_FCyumw" id="(0.5397727272727273,0.07954545454545454)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_pZqgsM5gEe2loO5JO7P1nQ" type="4001" element="_pZp5oM5gEe2loO5JO7P1nQ" source="_pZZa8M5gEe2loO5JO7P1nQ" target="_gyrFUs1mEe2_GaC9xHNsqQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_pZqgs85gEe2loO5JO7P1nQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_pZqgtM5gEe2loO5JO7P1nQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_pZqgsc5gEe2loO5JO7P1nQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_pZqgss5gEe2loO5JO7P1nQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
